### ISSUE TITLE
ValueError: Columns must be same length as key

### ISSUE THREAD

**Issue by huh688** [dblhlx/PyBSASeq#2] opened 2021-11-17 01:47 UTC
Got an error when loaded GATK result with PyBSASeq BulksOnly script. 

My GATK result was extracted from a joint call VCF with VariantsToTable, and converted to CSV format.

`Perform SNP filtering
Traceback (most recent call last):
  File "PyBSASeq.py", line 992, in <module>
    bsaSNPs = snpFiltering(snpRawDF)
  File "PyBSASeq.py", line 156, in snpFiltering
    df_2ALT_Real[['REF', 'ALT']] = df_2ALT_Real['ALT'].str.split(',', expand=True)
  File "/Users/haohu/miniconda3/envs/PyBSASeq/lib/python3.6/site-packages/pandas/core/frame.py", line 3041, in __setitem__
    self._setitem_array(key, value)
  File "/Users/haohu/miniconda3/envs/PyBSASeq/lib/python3.6/site-packages/pandas/core/frame.py", line 3067, in _setitem_array
    raise ValueError("Columns must be same length as key")
ValueError: Columns must be same length as key `

**Comment by dblhlx** [comment] 2021-11-20 09:51
VariantsToTable generates a TSV file, not a CSV file. Would you please change the file extension of your input file to TSV and run the script again. Attach the 2altReal_Before.csv file to your reply if encountering the same problem. The file is located in /your working directory/Results/FilteredSNPs/.

**Comment by huh688** [comment] 2021-11-21 00:33
I tried TSV and got the same error. But I don't have any problem to run your "bulks.csv" from data sample folder.
I'm attaching my input file "output3.test.tsv" and "2altReal_Before.csv" (empty) for further investigation.

[2altReal_Before.csv](https://github.com/dblhlx/PyBSASeq/files/7575564/2altReal_Before.csv)
[output3.test.tsv.gz](https://github.com/dblhlx/PyBSASeq/files/7575565/output3.test.tsv.gz)

**Comment by dblhlx** [comment] 2021-11-21 19:15
The error was caused by the empty dataframe. Code modified, please test again. Thanks very much for reporting bugs and please let me know if you have any questions.

BTW, there are some problems in your input file. The REF/ALT alleles in the genotype columns should be separated by "/", not "|". The SNP with "|" would be discarded by the script.

**Comment by huh688** [comment] 2021-11-21 19:57
Thanks for the quick fix, problem is solved now!

I'm using GATK 4.1.4.0, and it seems GATK4 supported phased variant ("|" or "/"), and it can be disabled by using "--do-not-run-physical-phasing" in HaplotypeCaller.

https://github.com/broadinstitute/gatk/releases/tag/4.0.12.0

As stated in VCF specification, "/" is genotype unphased, and "|" is genotype phased in GT field.

http://samtools.github.io/hts-specs/VCFv4.3.pdf

My project doesn't involve phased variants, but if would be best if you can support it in future.

**Comment by dblhlx** [comment] 2021-11-21 20:43
Thanks for the info. Just modified the script so the GT field can be splited with either '/' or '|'. I'll close this issue now.

**Closed as completed** 2021-12-10 16:48 UTC
